version: '3.9'

services:
  optimistic-postgres:
    build:
      context: src/main/resources/postgres
      dockerfile: Dockerfile
    command: postgres -c 'max_connections=1000'
    container_name: optimistic-postgres
    image: udinfopark/optimistic-postgres:latest-dev
    environment:
      TZ: "Europe/Budapest"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - src/main/resources/postgres/postgresql-server.env
    ports:
      - 2232:5432
    restart: "no"
    volumes:
      -  ./src/main/resources/postgres/initdb:/docker-entrypoint-initdb.d
      - optimistic_postgres_data:/var/lib/postgresql/data/pgdata

volumes:
  optimistic_postgres_data:
    external: true